import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import 'lenis/dist/lenis.css'
import { cn } from "@/lib/utils";
import LayoutClient from "@/components/templates/LayoutClient";

const urbanist = Urbanist({ subsets: ["latin"],variable:'--font-sans' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans dark")} style={{ colorScheme: 'dark' }}>
      <body className={urbanist.className + " min-h-[100dvh]"}>
        {/* <TargetCursor spinDuration={4.5} hideDefaultCursor parallaxOn hoverDuration={0.2}/> */}
        <LayoutClient>
          {children}
        </LayoutClient>
      </body>
    </html>
  );
}
